# Generated by Django 3.1.1 on 2020-11-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
