# Generated by Django 3.1.1 on 2020-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2020-11-14'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_people',
            field=models.IntegerField(default='5'),
        ),
    ]
