# Generated by Django 3.1.1 on 2020-11-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20201103_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='foodid',
            new_name='foodId',
        ),
    ]
